/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ccho' at '8/28/17 10:05 AM' with Gradle 2.14.1
 *
 * @author ccho, @date 8/28/17 10:05 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
